# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Vrjthr3fZ1_omqFYsYt07AOfhJajnvP

Questão 1
"""

email = input('Digite o email: ') #ler a variável email
login = '' #variável vazia
dominio = '' #variável vazia
for i in range(len(email)): #pegando toda a string
  email.find('@') #encontre o @
  if email[i] == '@': #quando o indice for o @
    login += email[:i] #pegue tudo antes dele
    dominio += email[i+1:] #pegar tudo que vem depois dele, por isso o =1 e os dois pontos
print(f'Login: {login} \nDominio: {dominio}')

#professor

"""Questão 2"""

frase = input('Digite a frase: ').upper()
for caracter in frase:
  if caracter == 'A':
    print(' ',end='')
  elif caracter =='E':
   print('U',end='')
  elif caracter =='I':
   print('O',end='')
  elif caracter =='O':
   print('I',end='')
  elif caracter =='U':
   print('E',end='')
  elif caracter ==' ':
   print('A',end='')
  else:
    print(caracter,end='')

"""Questão 3"""

nome = input('Nome: ').upper()
n1 =
for i in range(len(nome)):
  if nome[i] == 0
   n1 += nome[i]
  elif nome[i]

nome = input('Nome completo: ').upper()
vetor = nome.split()
print(vetor[-1],', ', sep='',end='')
for i in range(len(vetor)-1):
  print(vetor[i][0], '. ', sep='', end='')

"""Questão 4"""

frase = input('Digite: ')
n = int(input('Digite um número inteiro: '))
for i in range(len(frase)):
  if frase[i] == 'a' or frase[i] == 'e' or frase[i] == 'i' or frase[i] == 'o' or frase[i] == 'u':
    mult = frase[i]*n
  else:
    mult = frase[i]
  print(mult, end='')

"""Questão 5"""

frase = input('Frase: ')
for e in frase:
  if frase[0]:
    print(frase[0])
  if frase[1]:
    print(frase[1]*2)
  if frase[2]:
    print(frase[2]*3)
  if frase[3]:
    print(frase[3]*4)
  if frase[4]:
   print(frase[4]*5)
  if frase[-1]:
   print(frase[-1]*5)
  if frase[-2]:
    print(frase[-2]*4)
  if frase[-3]:
    print(frase[-3]*3)
  if frase[-4]:
    print(frase[-4]*2)

#professor
frase = input('Frase:\n')
n = len(frase)

print('\nSaída:')

#pegar a primera leva
for i in range(n):
    print(frase[i]*(i+1))

#pegar a segumda leva
for i in range(n-2,-1,-1):
    print(frase[i]*(i+1))

"""Questão 6"""

verbo = input('Verbo: ')
n = len(verbo)
radical = verbo[:-2]
for i in range(1):
  if verbo[-2:] == 'ar':
    print(f'Eu {radical}o \nTu {radical}as \nEle {radical}a \nNós {radical}amos \nVós {radical}ais \nEles {radical}am')
  if verbo[-2:] == 'er':
    print(f'Eu {radical}o \nTu {radical}es \nEle {radical}e \nNós {radical}emos \nVós {radical}eis \nEles {radical}em')
  if verbo[-2:] == 'ir':
    print(f'Eu {radical}o \nTu {radical}es \nEle {radical}e \nNós {radical}imos \nVós {radical}is \nEles {radical}em')

#professor
ta = ['o','as','a','amos','ais','am']  #terminações dos verbos terminados em AR
te = ['o','es','e','emos','eis','em']  #terminações dos verbos terminados em ER
ti = ['o','es','e','imos','is','em']   #terminações dos verbos terminados em IR
pes = ['Eu','Tu','Ele','Nós','Vós','Eles']

verbo = input('Entre com um verbo regular no infinitivo: ').lower()

tam = len(verbo)  #tamanho do verbo
vt = verbo[-2]  #vogal temática
rad = verbo[:tam-2]  #radical

if vt == 'a':
    for i in range(6):
        print(f'{pes[i]} {rad}{ta[i]}')
elif vt == 'e':
    for i in range(6):
        print(f'{pes[i]} {rad}{te[i]}')
else:
    for i in range(6):
        print(f'{pes[i]} {rad}{ti[i]}')