# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAMEhvgZtisCQ3rHe9Dcud9K859v7Pks

QUESTÃO 1
"""

def vogal(letra):
  if letra in 'AaEeIiOoUu':
    return True
  else:
    return False
frase = input('Digite uma frase: ')
cont = 0
for caracter in frase:
  if vogal(caracter): #função
    cont += 1
print(f'A frase contém {cont} vogal(is)')

def vogal(letra):
  return letra in 'AaEeIiOoUu'
frase = input('Digite uma frase: ')
cont = 0
for caracter in frase:
  if vogal(caracter): #função
    cont += 1
print(f'A frase contém {cont} vogal(is)')

"""QUESTÃO 2"""

def primo(n):
  if n == 1: #exceção
    return False
  for i in range(2,n): #comece do 2 até o número inserido
    if n % i == 0: #se o resto for 0 não é primo
      return False
  return True

print('Números primos entra 1 e 100: ')
for i in range(1,101):
  if primo(i):
    print(i,' ',end='')

"""QUESTÃO 3"""

#obs: para chamar um função tem que ser na ordem que ela está criada
def ler_vetor(n):
  v = [None]*n #vetor vazio
  for i in range(n): #para cada vetor
    v[i] = int(input('Digite os elementos do vetor: '))
  return v

def media_vetor(v):
  return sum(v)/len(v)

def cont_vetor(v,t):
  cont  = 0  #inicia a variável
  for elem in v: #testa o elemento
    if elem < t: #se for menor
      cont +=1 #adicione ao contador
  return cont

n = int(input('Digite a quantidade de números no vetor: '))
x = ler_vetor(n)
media = media_vetor(x)
quant = cont_vetor(x,media)
print(f'Existem {quant} elementos abaixo da média({media:.2f})')

"""QUESTÃO 4"""

def ler_matriz(lin,col):
  m = [[None]*col for i in range(lin)]
  for i in range(lin):
    for j in range(col):
      m[i][j] = int(input())
  return m

def imp_matriz(m):
  lin = len(m)
  col = len(m[0])
  for i in range():
    for j in range():
      print(f'{m[i][j]:4}', end='')
    print()

def soma_matriz(a,b):
  lin = len(a)
  col = len(a[0])
  c = [[None]*col for i in range(lin)]
  for i in range(lin):
    for j in range(col):
      c[i][j] = a[i][j] + b[i][j]
  return c

print('Digite a ordem das matrizes: ')
lin = int(input('Nº de linhas: '))
col = int(input('Nº de colunas: '))
m1 = ler_matriz(lin,col)
m2 = ler_matriz(lin,col)
m3 = soma_matriz(lin,col)
imp_matriz('1ª matriz: ',m1)
imp_matriz('2ª matriz: ',m2)
imp_matriz('3ª matriz: ',m3)

"""QUESTÃO 5"""

def fatorial(n):
  fat = 1
  for i in range(1,n+1):
    fat *= i
  return fat

def potencia(b,e):
  return b**e

import math
soma = 0
n = 0
x = float(input('Digite o valor do cosseno: '))
for i in range(1,21):
  termo = potencia(x,n)/fatorial(n)
  if i % 2 == 1:
    soma += termo
  else:
    soma -= termo
  n += 2
print(soma)
print(math.cos(x))