# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgUN9a58jk6Hn2xSEVT8mzrL_Xs3qbSe

**QUESTÃO 1**
"""

frase = input('Digite: ') #pra digitar o desejado
quant = frase.count(' ') #contador de branco
print(f'A frase contém {quant} brancos')

"""**QUESTÃO 2**"""

frase = input('Frase: ')
saida = ''
for caracter in frase:
  if caracter != ' ': #se o caracter diferente de branco
    saida += caracter #adicione  saida e o caracter
print(saida)

frase = input('Digite: ')
saida = frase.replace(' ', '') #troca o branco por nada
print(saida)

frase = input('Frase: ')
for caracter in frase:
  if caracter != ' ': #se o caracter diferente de branco
   print(caracter, end='')

"""**QUESTÃO 3**"""

frase = input('Frase: ')
saida = frase.upper() #deixa maiúsculo
print(saida)

frase = input('Digite uma frase: ').upper()
print(frase)

#usando a tabela ASCII e não a função upper
frase = input('Frase: ')
saida = '' #saida é nada
for caracter in frase:
  if caracter >= 'a' and caracter <= 'z':
    saida += chr(ord(caracter)-32) #pegar a ordem do número
  else:
    saida += caracter #se não for minúsculo
print(saida)

#usando a tabela ASCII e não a função upper
frase = input('Frase: ')
saida = '' #saida é nada
dif = ord('a') - ord('A')
for caracter in frase:
  if caracter >= 'a' and caracter <= 'z':
    saida += chr(ord(caracter)-dif) #pegar a ordem do número
  else:
    saida += caracter #se não for minúsculo
print(saida)

"""**QUESTÃO 4**"""

frase = input('Frase: ')
saida = frase.title()
print(saida)

frase = input('Frase: ')
saida = ''
for i in range(len(frase)):
  if i == 0: #se for a primeira letra
    saida += frase[i].upper()
  elif frase[i-1] == ' ':
    saida += frase[i].upper() #as letras restantes
  else:
    saida += frase[i].lower() #ficar igual ao título
print(saida)

"""**QUESTÃO 5**"""

frase = input('Frase: ')
tam = len(frase)
for i in range(tam):
   print(frase[i]) #o print já quebra a linha automaticamente

"""**QUESTÃO 6**"""

frase = input('Digite: ')
tam = len(frase)
for i in range(tam-1,-1,-1): #um for de trás pra frente
  print(frase[i], end='')

frase = input('Digite: ')
tam = len(frase)
for i in range(tam):
  print(frase[tam - i - 1], end='') #COLOCANDO A FÓRMULA NO I --> SE O I = 0 --> 5-0-1

frase = input('Digite: ')
tam = len(frase)
print(frase[::-1]) #do início ao fim pegando -1

"""***EU***"""











