# -*- coding: utf-8 -*-
"""APE_EXERCICIOS_17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9vKANonCNo4HGNbT6Emx_T1JKFg8plg
"""

nomearq = input('Digite o nome do arquivo: ')
arq = open(nomearq,'r')
text = arq.read()
print(text)
arq.close()

nomearq = input('Nome do arquivo: ')
arq = open(nomearq,'r')
cop = open('COPIA.TXT')

arq = open('Arquivo.txt','w')
arq.write('Primeira linha\n')
arq.close()
print('Arquivo gerado com sucesso!')

nomearq = input('Digite o nome do arquivo')
arq = open(arquivo.txt,'w')
arq.write('Primeira linha\n')
arq.close()
print(f'Arquivo {nomearq} gerado com sucesso!')

nomearq = input('Digite o nome do arquivo')
arq = open(nomearq,'a')
arq.write('Quarta linha\n')
arq.close()
print(f'Nova linha adicionada com sucesso!')

arq = open('arquivo.txt','w')
arq.write('Primeira Linha/nSegunda ')