# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HcErNRcnczbY81hTlcisc0j3DroYHly

***QUESTÃO 5***
"""

#PROFESSOR
arq = open(nomearq,'w')
linha =
arq.write = (linha +)
arq.write(texto)
arq.close()
print('\nLinha inserida com sucesso!')

"""***QUESTÃO 6***"""

#PROFESSOR
nomearq1 = input('1º Arquivo: ') #tem que criar os 3 arquivos na biblioteca
nomearq2 = input('2º Arquivo: ') #no arq1 e no ar2 tem que ter informações a serem lidas
nomearq3 = input('3º Arquivo: ') #para ocorrer deve-se fazer o upload


arq1 = open(nomearq1,'r') #pega info
arq2 = open(nomearq2,'r') #pega info
arq3 = open(nomearq3,'w') #grava info dos dois


texto1 = arq1.read()  #a ação
texto2 = arq2.read()
texto3 = texto1 + texto2 #recebe as duas e faz outra/contatenar
'''
outra opção:
1º coloca
arq3.write(texto1)
arq3.write(texto2)
2º retira
arq3.write(texto3)
assim, utilizando dois writtings/ sem contatenação
'''

arq3.write(texto3) #mostrar a ação

arq1.close() #fechar os arquivos
arq2.close()
arq3.close()

"""***QUESTÃO 7***"""

#PROFESSOR
arq = open(nomearq,'r')
text = arq.read()
tamanho = len(texto)

"""***QUESTÃO 8***"""

#PROFESSOR
'''
UTILIZANDO DADOS
INTERESSANTE PARA O PROJETO
'''
#criar um arquvo com o nome cadastro

arq = open('cadastro.txt', 'w')
print('Digite os dados abaixo:\nPara finalizar aperte a tecla enter.')
while True:
  nome = input('\nNome: ')
  if nome == '':
    break
  sexo = input('Sexo(M/F): ').upper()
  idade= int(input('Digite a idade: '))
  linha = nome+','+sexo+','+str(idade)+'\n'
  arq.write(linha)
arq.close

"""***QUESTÃO 9***"""

#PROFESSOR
arq = open(cadastro.txt,'r')
sm = 0
sf = 0
cm = 0
cf = 0
for linha in range