# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVjrNWrW4XF4tip_ZhpLsQ0Yz39fOe3k

**QUESTÃO 1**

Escreva um programa que leia um vetor contendo N elementos inteiros (N será
lido), calcule e exiba:
• A quantidade de elementos pares;
• A quantidade de elementos ímpares;
• A soma de todos os elementos;
• A média dos elementos do vetor.
"""

#PROFESSOR

import random
n = int(input('Digite o tamanho do vetor: '))
v = []
vp = []
vi = []

for i in range(n):
  numero = random.randint(1,30) #aleatório
  v.append(numero)
  if numero % 2 == 0:
    vp.append(numero) #adiciona os elementos
  else:
    vi.append(numero)
print('Vetor: ',*v)
print('Pares: ',*vp)
print('Ímpares: ',*vi)


contp = len(vp) #conta o tamanho do vetor
conti = len(vi)
soma = sum(v)
media = soma/n


print(f'A quantidade de elementos pares: {contp}')
print(f'A quantidade de elementos ímpares: {conti}')
print(f'A soma de todos os elementos: {soma}')
print(f'A média dos elementos do vetor: {media}')

#PROFESSOR

import random
n = int(input('Digite o tamanho do vetor: '))
v = [None]*n

for i in range(n):
  v[i] = random.randint(1,30)
print(*v)

contp = 0
conti = 0
soma = 0
for e in v:
  if e % 2 == 0:
    contp +=1
  else:
    conti += 1
  soma += e
media = soma/n
print(f'A quantidade de elementos pares: {contp}')
print(f'A quantidade de elementos ímpares: {conti}')
print(f'A soma de todos os elementos: {soma}')
print(f'A média dos elementos do vetor: {media}')

#EU
n = int(input('Digite a quantidade de elementos no vetor: '))
v = [None]*n

#definir as variáveis que vou precisar:
quantp = 0
quanti = 0
soma = 0

#um for para a repetição de adicionar número:
for i in range(n):
 v[i] = int(input('Digite um número: '))

#um for para encontrar o que eu preciso:
for e in v: #e vai ser o elemento dentro de v, o vetor
 if e % 2 == 0:
  quantp += 1
 else:
  quanti += 1
 soma += e #eu quero o zero da soma mai so valor do elemento
media = soma/n #n é a quantidade de números, ou seja o total

#um for para mostrar os que são pares
for e in v:
  if e % 2 == 0:
    print(f'O número {e} é par.')
  else:
    print(f'O número {e} é ímpar.')
print(f'pares: {quantp}')
print(f'ímpares: {quanti}')
print(f'soma: {soma}')
print(f'média: {media}')

"""**QUESTÃO 2**

Dados dois vetores A e B contendo N elementos inteiros cada (N, A e B serão
lidos), gerar e exibir um vetor C (de tamanho N*2) cujos elementos sejam a
intercalação dos elementos de A e B.
Ex: N = 3, A = [18, 12, 20], B = [15, 10, 7], C = [18, 15, 12, 10, 20, 7]
"""

import random

n = int(input('Digite o número de elementpos do vetor: '))
a = [None]*n
b = [None]*n
c = [None]*n*2 # vai receber n e multiplicar por 2, já que quer o dobro

for i in range(n):
  a[i] = random.randint(1,20)

for i in range(n):
  b[i] = random.randint(1,20)

for i in range (n): #se o n for 6 vai até 5
 c[i*2] = a[i] #pega o a, depois pega o b #quando for o a é sempre o dobro
 c[i*2+1] = b [i] #quando for b a relação é o dobro mais 1

print('A = ',*a) #a multiplicação é só pra não sair com os colchetes
print('B = ',*b)
print('C = ',*c)

import random

n = int(input('Digite o número de elementpos do vetor: '))
a = [None]*n
b = [None]*n
c = [None]*n*2 # vai receber n e multiplicar por 2, já que quer o dobro

for i in range(n):
  a[i] = random.randint(1,20)

for i in range(n):
  b[i] = random.randint(1,20)

for i in range (n*2):
  if i%2 == 0:
    c[i] = a[i//2] #divide já que é pra encontrar a metade
  else:
    c[i] = b [i//2]

print('A = ',a)
print('B = ',b)
print('C = ',c)

#EU
#definir as variáveis e os vetores:
n = int(input('Digite a quantidade de elementos no vetor: '))
a = [None]*n
b = [None]*n #tem que ter o none
c = [None]*n*2

#os elementos de acordo com seus vetores:
print('Digite os elementos do vetor a: ')
for i in range(n):
  a[i] = int(input())

print('Digite os elementos do vetor b: ')
for i in range(n):
  b[i] = int(input())

#para colocar dentro de c
for i in range(n):
  c[i*2] = a[i]
  c[i*2+1] = b[i]

print(f'A = {a}')
print(f'B = {b}')
print(f'C = {c}')

"""**QUESTÃO 3**
Escreva um programa para ler 6 números. Após a leitura dos números, verifique,
para cada um deles, se é distinto, ou seja, não possui repetição.
 ***in é para dizer que está dentro de algo, ou seja contido***
"""

#PROFESSOR
v = [None]*6
print('Digite 6 números inteiros: ')
for i in range(6):
  v[i] = int(input())

for e in v:
  if v.count(e) > 1:
    print(e,'se repete.')
  else:
    print(e,'não se repete')

#PROFESSOR
v = []
vr = []
vn = []
print('Digite 6 números inteiros: ')
for i in range(6):
  v.append(int(input()))
print()
for e in v:
  if v.count(e) > 1 and e not in vr:
     vr.append(e)
  if v.count(e) <=1 and e not in vn:
    vn.append(e)
print('Número: ',*v)
print('Números repetidos: ',*vr)
print('Números não repetidos: ',*vn)

#PROFESSOR
import random
v = []
vr = []
vn = []
print('Digite 6 números inteiros: ')
for i in range(6):
  v.append(random.randint)
print()
for e in v:
  if v.count(e) > 1 and e not in vr:
     vr.append(e)
  if v.count(e) <=1 and e not in vn:
    vn.append(e)
print('Número: ',*v)
print('Números repetidos: ',*vr)
print('Números não repetidos: ',*vn)

#EU
import random
v = [None]*6
vr = []
vn = []
for i in range(6):
  v[i] = random.randint(1,6)
for e in v:
  if v.count(e) > 1:
    print(e,'se repete.')
  else:
    print(e,'não se repete')

v = [None]*6
cont = 1
for i in range(6):
  v[i] = int(input('Digite um número: '))
if v[i] > cont:
    print('Há repetições no vetor abaixo.')
else:
    print('Não há repetições no vetor abaixo.')
print(v)

"""**QUESTÃO 4**

Escreva um programa para ler 6 números distintos, ou seja, não podem repetir.
Exiba os números lidos.
"""

#PROFESSOR
v = []
while True:
  n = int(input('Digite um número inteiro: '))
  if n not in v:
     v.append(n) #vai adicionar
  else:
    print('Número já existente.') #se o número já existe ele não coloca dentro do vetor, nem conta no 6
  if len(v) == 6:  #vai repetir até o tamanho chegar em 6
    break
print(v)



"""**QUESTÃO 5**

Faça um programa para ler as 8 dezenas apostadas por 20 apostadores e
verificar se a aposta é válida (cada dezena está entre [1, 80] e não pode haver
repetição). O programa deverá calcular e exibir a quantidade de números
acertados em cada aposta.
Atenção! As dezenas sorteadas são: 06, 07, 13, 14 e 26.
"""

vda = [None]*8
vs = [6,7,13,14,26]

for i in range(20): #pegar os 20 apostadores
  pontos = 0
  for j in range(8): #pegar as apostas de cada um
    vda[j] = int(input('Digite a dezena: '))
  for dezena in vda:
    if dezena<1 or dezena>80 or vda.count(dezena)>1:
      print('Aposta inválida')
      break
    else:
      if dezena in vs:
         pontos += 1
  print('Aposta: ', vda)
  print('Sorteio: ', vs)
  print('Pontos: ', pontos)
  print()



"""**QUESTÃO 6**

O Brasil possui 26 estados e 1 distrito federal, totalizando 27 unidades
federativas. Escreva um programa para armazene, em um vetor, a sigla de todas
as unidades federativas. O programa deverá obter de vários usuários qual é a
unidade federativa ele acha mais interessante, informando a respectiva sigla. O
programa encerra quando for digitada uma sigla inexistente. Ao final, o
programa deverá exibir qual foi a sigla mais votada (considere possibilidade de
empate).
"""

