# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eY3fnZEsrBvO_Y4uvGUHK9UB07qY6X_S
"""

nome = input('Digite o nome do funcionário: ')
quantcar = int(input('Digite aqui a quantidade de carros vendidos: '))
valorvenda = int(input('Digite o valor da venda dos carros: '))
salario = 1000
comis = int((200 * quantcar))
carsell = int((0.05 * valorvenda))
saltotal = int(salario + comis + carsell)
print(f'O salário total do funcionário {nome} é igual a R${saltotal}')

nome = input('Digite o nome do aluno: ')
n1 = float(input('Digite a primeira nota do aluno: '))
p1 = 6
n2 = float(input('Digite a segunda nota do aluno: '))
p2 = 4
mediaPond = float(n1*p1+n2*p2)/(p1+p2)
print(f'A média ponderada do aluno {nome} é igual a {mediaPond}: ')

x = int(input("Digite um valor para x: "))
y = int(input("Digite um valor para y: "))
print('Antes da troca:')
print('x =', x)
print('y =',y)

aux = x
x = y
y = aux

print('Depois da troca;')
print('x =',x)
print('y =',y)

hodant = int(input('Digite o valor do hodômetro antes da viagem: '))
lantes = int(input('Digite a quantidade de litros antes do percurso: '))
hoddep = int(input('Digite o valor do hodômetro após a viagem: '))
ldepois = int(input('Digite a quantidade de litros depois do percurso: '))
captanq = int(input('Digite a capacidade máxima do tanque do veículo: '))
precocom = float(input('Digite o valor do litro da gasolina: '))
hodzero = float(input('Zere o hodômetro parcial. '
                   'Digite a quantidade de Km rodados até finalizar o tanque cheio: '))
quirod = int(hoddep - hodant)
lgastos = int(lantes - ldepois)
quiporl = int(quirod/lgastos)
autovel = int(hodzero//captanq)
custoviag = int(precocom * quirod)
print(f'A quantidade de quilômetros rodados foi {quirod}, de litros gastos {lgastos}.')
print(f'O carro roda {quiporl}Km/L.')
print(f'Sua autonomia é de {autovel}.')
print(f'E o custo total da viagem foi de R${custoviag}.')

segundos = int(input('Digite um valor inteiro em segundos: '))
minutos = int(segundos//60)
horas = int(minutos//60)
print(f'A quantidade em horas: {horas}.')
print(f'A quantidade em minutos: {minutos}.')
print(f'A quantidade em segundos: {segundos}.')

dinDes = int(input('Digite o valor desejado: '))

notas50 = int(dinDes//50)
resto50 = dinDes % 50
notas10 = int(resto50//10)
resto10 = resto50 % 10
notas5 = int(resto10//5)
resto5 = resto10 % 5
notas1 = int(resto5//1)
resto1 = resto5 % 1

print(f'A quantidade em notas de B$50: {notas50}.')
print(f'A quantidade em notas de B$10: {notas10}.')
print(f'A quantidade em notas de B$5: {notas5}.')
print(f'A quantidade em notas de B$1: {notas1}.')