# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uK5Knu4T9fKpyuJ1h1h8K-mxkL2Blqr

QUESTÃO 1
Escreva um programa que preencha duas matrizes (A e B), ambas de ordem 2x3, com
valores inteiros fornecidos pelo usuário (ou gerados aleatoriamente). O programa
deverá somar as duas matrizes, armazenando o resultado em uma terceira matriz (C).
Ao final, exiba as 3 matrizes (no formato de matriz).
"""

#EU/AJUDA
nlin = 2
ncol = 3

a = [[None]*ncol for i in range(nlin)]
b = [[None]*ncol for i in range(nlin)] #vai ter que multiplca para pegar a quantidade de linhas e colunas
c = [[None]*ncol for i in range(nlin)]

print('Digite os elementos da matriz A: ')
for i in range(nlin):
  for j in range(ncol):
    a[i][j] = int(input(f'A[{i}][{j}]: ')) #leitura

print()
print('Digite os elementos da matriz B: ')
for i in range(nlin):
  for j in range(ncol):
    b[i][j] = int(input(f'B[{i}][{j}]: '))

print()
for i in range(nlin):
  for j in range(ncol):
    c[i][j] = a[i][j] + b[i][j] # somo os dois de cada para darem os dois desse

print('Matriz A: ') # aqui é só a impressão dela, tem que ter
for i in range(nlin):
  for j in range(ncol):
    print(f'{a[i][j]:4}',end=' ')
print()

print('Matriz B: ') # o outro é só a leitura
for i in range(nlin):
  for j in range(ncol):
    print(f'{b[i][j]:4}',end=' ')
print()

print('Matriz C: ') # para cada um eu tenho que ler e imprimir
for i in range(nlin):
  for j in range(ncol):
        print(f'{c[i][j]:4}',end='')
  print()

#PROFESSOR
import random

nlin = 2  # número de linhas da matriz
ncol = 3  # número de colunas da matriz

# Criação das matrizes
a = [[None]*ncol for i in range(nlin)]
b = [[None]*ncol for i in range(nlin)]
c = [[None]*ncol for i in range(nlin)]

# Preenchimento aleatório da matriz A
for i in range(nlin):
    for j in range(ncol):
        a[i][j] = random.randint(1,10)

# Preenchimento aleatório da matriz B
for i in range(nlin):
    for j in range(ncol):
        b[i][j] = random.randint(1,10)

# Cálculo da matriz C
for i in range(nlin):
    for j in range(ncol):
        c[i][j] = a[i][j] + b[i][j]

# Impressão da matriz A
print('\nMatriz A:')
for i in range(nlin):
    for j in range(ncol):
        print(f'{a[i][j]:4}',end='')
    print()

# Impressão da matriz B
print('\nMatriz B:')
for i in range(nlin):
    for j in range(ncol):
        print(f'{b[i][j]:4}',end='')
    print()

# Impressão da matriz C
print('\nMatriz C:')
for i in range(nlin):
    for j in range(ncol):
        print(f'{c[i][j]:4}',end='')
    print()

"""QUESTÃO 2
Escreva um programa que:
• Leia (ou gere aleatoriamente) uma matriz quadrada de ordem N contendo elementos
inteiros (N será lido);
• Exiba a matriz lida (no formato de matriz);
• Exiba os elementos da diagonal principal, isto é, os elementos onde I = J.
"""

#EU/AJUDA
import random

n = int(input('Digite a ordem da matriz: ')) #dizer a quantidade de colunas e tabelas
print()

m = [[None]*n for i in range(n)] #formar a matriz de fato

for i in range(n):
  for j in range(n):
    m[i][j] = random.randint(1,20) #pegar os valores da matriz

print('Matriz: ') #impressão da matriz
for i in range(n):
  for j in range(n):
    print(f'{m[i][j]:4}', end=" ") #seu formato
  print() #pra ter o espaço na matriz
print() #ter espaço entre os comandos

print('Diagonal principal: ')
for i in range(n):#tem que fazer toda essa estrutura
  for j in range(n):  #p/ que ele entenda que é com os dois
   if i == j:
    print(f'{m[i][j]:4}', end=" ")

import random

n = int(input('Digite a ordem da matriz: ')) #dizer a quantidade de colunas e tabelas
print()

m = [[None]*n for i in range(n)] #formar a matriz de fato

for i in range(n):
  for j in range(n):
    m[i][j] = random.randint(1,20) #pegar os valores da matriz

print('Matriz: ') #impressão da matriz
for i in range(n):
  for j in range(n):
    print(f'{m[i][j]:4}', end=" ") #seu formato
  print() #pra ter o espaço na matriz

print() #ter espaço entre os comandos

print('Diagonal principal: ')
for i in range(n):
  print(f'{m[i][i]:4}', end=" ")
print()

#PROFESSOR
# Leitura da ordem da matriz quadrada
n = int(input('Digite a ordem da matriz: '))

# Criação da matriz
m = [[None]*n for i in range(n)]

# Leitura da matriz
print('\nDigite os elementos da matriz:')
for i in range(n):
    for j in range(n):
        m[i][j] = int(input(f'm[{i}][{j}]: '))

# Exibição da matriz
print('\nMatriz:')
for i in range(n):
    for j in range(n):
        print(f'{m[i][j]:4}',end='')
    print()

# Exibição da diagonal principal
print('\nDiagonal Principal:')
for i in range(n):
    print(f'{m[i][i]:4}',end='')

"""QUESTÃO 3
Escreva um programa que gere aleatoriamente uma matriz quadrada A (cuja ordem
será lida) e gere uma matriz B (da mesma ordem de A), onde cada elemento de B
corresponderá ao respectivo elemento de A somado a ele os seus índices, sendo que se
o elemento for de alguma diagonal (principal ou secundária) deverá ser colocado 0
(zero).
Veja o exemplo a seguir:

Ao final, imprima as duas matrizes (no formato de matriz).
"""

#EU/AJUDA
import random

n = int(input('Digite a ordem da matriz: '))
print()

a = [[None]*n for i in range(n)]
b = [[None]*n for i in range(n)]

for i in range(n):
  for j in range(n):
    a[i][j] = random.randint(1,20)

for i in range(n):
  for j in range(n):
    if  b[i] == b[j] or i + j == n - 1: #se os índices iguais #o 2° tem que ter para a diagonal no outro sentido
     b[i][j] = 0
    else: #tem que botar a variação para quando não são iguais
     b[i][j] = a[i][j] + i + j

print('Matriz A:')
for i in range(n):
  for j in range(n):
    print(f'{a[i][j]:3}', end=" ") #impressão é separadaaaa
  print() #tem que tá dentro do laço

print()

print('Matriz B:')
for i in range(n):
  for j in range(n):
    print(f'{b[i][j]:3}', end=" ")
  print()

#PROFESSOR
import random

#leitura da ordem das matrizes
ord = int(input('Ordem das matrizes: '))

#inicialização das variáveis
A = [[None]*ord for i in range(ord)]
B = [[None]*ord for i in range(ord)]

#geração aleatória da matriz A
for lin in range(ord):
    for col in range(ord):
        A[lin][col] = random.randint(1,20)

#geração da matriz B
for lin in range(ord):
    for col in range(ord):
        if lin == col or lin + col == ord - 1:
            B[lin][col] = 0
        else:
            B[lin][col] = A[lin][col] + lin + col

#impressão da matriz A
print('\nMatriz A')
for lin in range(ord):
    for col in range(ord):
        print(f'{A[lin][col]:3}',end='')
    print()

#impressão da matriz B
print('\nMatriz B')
for lin in range(ord):
    for col in range(ord):
        print(f'{B[lin][col]:3}',end='')
    print()

"""QUESTÃO 4
Uma matriz transposta é a matriz que se obtém da troca de linhas por colunas de uma
dada matriz.
Assim, dada uma matriz C de ordem m x n, a matriz transposta dela será representada
por Ct de ordem n x m, onde cada elemento de Ct[i,j] = C[j,i].

Escreva um programa que preencha uma matriz 3x5 com valores inteiros fornecidos
pelo usuário (ou gerados aleatoriamente) e gere a sua transposta. Ao final, imprima as
duas matrizes (no formato de matriz).
"""

#EU
import random

m = int(input('Digite a quantidade de linhas: '))
n = int(input('Digite a quantidade de colunas: '))

c = [[None]*n for i in range(m)]
ct = [[None]*m for i in range(n)]

for i in range(m):
  for j in range(n):
    c[i][j] = random.randint(1,20)

for i in range(n):
  for j in range(m):
    ct[i][j] = c[j][i]

print('Matriz:')
for i in range(m):
  for j in range(n):
    print(f'{c[i][j]:3}', end=" ")
  print()

print('Matriz Transposta:')
for i in range(n):
  for j in range(m):
    print(f'{ct[i][j]:3}', end=" ")
  print()

#PROFESSOR
import random

x = 3  # número de linhas da matriz M
y = 5  # número de colunas da matriz M

# Criação das matrizes
m = [[None]*y for i in range(x)]
t = [[None]*x for i in range(y)]

# Leitura da matriz M
print('Digite os elementos da Matriz M:')
for i in range(x):
    for j in range(y):
        m[i][j] = random.randint(1,30)

# Geração da matriz T (transposta)
for i in range(x):
    for j in range(y):
        t[j][i] = m[i][j]

# Impressão da matriz M
print('\nMatriz M:')
for i in range(x):
    for j in range(y):
        print(f'{m[i][j]:4}',end='')
    print()

# Impressão da matriz T
print('\nMatriz T (transposta):')
for i in range(y):
    for j in range(x):
        print(f'{t[i][j]:4}',end='')
    print()

"""QUESTÃO 5
Escreva um programa que:
• Crie uma matriz de ordem 20 x 4 e armazene nela as 3 notas dos 20 alunos de uma
turma e a média de cada um deles.
o As notas serão lidas e armazenadas nas 3 primeiras colunas da matriz;
o As médias serão calculadas e armazenadas na 4a coluna da matriz.
• Imprima as notas dos alunos e suas respectivas médias (no formato de matriz).
• Calcule e imprima a média geral da turma.
• Calcule e imprima o número de alunos com média superior à média geral da turma.
"""

lin = 20
col = 3


m = [[None]*col for i in range(lin)]



#colocar as notas na matriz
for i in range(lin):
  for j in range(col):
   nome = input("Digite o nome do aluno: ")
   n1 = int(input("Digite a primeira nota do aluno: "))
   n2 = int(input("Digite a segunda nota do aluno: "))
   n3 = int(input("Digite a terceira nota do aluno: "))
   media = (n1+n2+n3)/3
#impressão da matriz
print('Tabela de notas: ')
for i in range(lin):
  for j in range(col-1):
   print(f'{m[i][j]:3}', end=" ")
  print()

maior = max(m)
print(f'A maior nota foi: {maior}.')

#PROFESSOR - AULA
nlin = 2 #para cálculo, usar o 2
ncol = 4

m = [[None]*ncol for i in range(nlin)]

#leitura da matriz
for i in range(nlin):
  print(f'Aluno {i+1}')
  for j in range(ncol-1): #ideia de matriz com 2 for (-1 pq para antes)
   m[i][j] = int(input(f'{j+1}º nota: '))

#cáculo das médias
for i in range(nlin):
  soma = 0
  for j in range(ncol):
   soma += m[i][j]
   print(soma)

#impressão da matriz
print(f'{"N1":>4} {"N2":>4} {"N3":>4} {"Média":5}')
for i in range(nlin):
  print(f'Aluno {i+1}',end='')
  for j in range(ncol):
   print(f'{m[i][j]:4}', end=" ")
  print()

#média geral
soma = 0
for i in range(nlin):
   soma += m[i][j]
mg = (soma/nlin)
print(f'Média geral: {mg}')


#alunos com nota maior que a média geral
cont = 0
for i in range(nlin):
    if media > mg:
        cont += 1
print(f'\nNúmero de alunos com média superior à média geral da turma: {cont}')

nlin = 2
ncol = 4

m = [[None]*ncol for i in range(nlin)]

#leitura das notas
for i in range(nlin):
    print(f'Aluno {i+1}:')
    for j in range(ncol-1):
        m[i][j] = int(input(f'{j+1}ª Nota: '))

#cálculo das médias
for i in range(nlin):
    soma = 0
    for j in range(ncol-1):
        soma += m[i][j]
    m[i][3] = round(soma/(ncol-1))

#imprimir a matriz
print(f'        {"N1":>4}{"N2":>4}{"N3":>4} {"Média"}')
for i in range(nlin):
    print(f'Aluno {i+1}',end='')
    for j in range(ncol):
        print(f'{m[i][j]:4}',end='')
    print()

#calcular a média geral
soma = 0
for i in range(nlin):
    soma += m[i][3]
mg = soma / nlin
print('Média geral:',mg)

#Calcular o número de alunos com média superior à média geral

cont = 0
for i in range(nlin):
    if m[i][3] > mg:
        cont += 1
print('Nº de alunos com média superior à média geral:',cont)

nlin = 2
ncol = 4

m = [[None]*ncol for i in range(nlin)]

#leitura das notas
for i in range(nlin):
    print(f'Aluno {i+1}:')
    for j in range(ncol-1):
        m[i][j] = int(input(f'{j+1}ª Nota: '))

#cálculo das médias
for i in range(nlin):
    soma = 0
    for j in range(ncol-1):
        soma += m[i][j]
    m[i][3] = round(soma/(ncol-1))

#imprimir a matriz
print(f'        {"N1":>4}{"N2":>4}{"N3":>4} {"Média"}')
for i in range(nlin):
    print(f'Aluno {i+1}',end='')
    for j in range(ncol):
        print(f'{m[i][j]:4}',end='')
    print()

#calcular a média geral
soma = 0
for i in range(nlin):
    soma += m[i][3]
mg = soma / nlin
print('Média geral:',mg)

#Calcular o número de alunos com média superior à média geral

cont = 0
for i in range(nlin):
    if m[i][3] > mg:
        cont += 1
print('Nº de alunos com média superior à média geral:',cont)