# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DuC1oEtDEq75Y8yAA-ZYAXvPlGWMFNkM

QUESTÃO 1
"""

import math
print(f'   x      raiz(x)    cubo(x)')
for x in range (50,301,5):
 raiz = math.sqrt(x)
 cubo = x ** 3
 print(f'{x:5} {raiz:10.4f} {cubo:10}')

import math
cab_1 = 'x'
cab_2 = 'raiz(x)'
cab_3 = 'cubo(x)'
print(f'{cab_1:>5} {cab_2:>10} {cab_3:>10}')
for x in range (50,301):
   if x % 5 == 0:
    raiz = math.sqrt(x)
    cubo = x ** 3
    print(f'{x:5} {raiz:10.4f} {cubo:10}')

import math
print(f'   x      raiz(x)    cubo(x)')
for x in range (50,301):
   if x % 5 == 0:
    raiz = math.sqrt(x)
    cubo = x ** 3
    print(f'{x:5} {raiz:10.4f} {cubo:10}')

"""QUESTÃO 2"""

n = int(input('Digite um número inteiro: '))
soma = 0
for i in range (1,n+1):
  soma += i
print(f'{soma}')

s = 0
n = int(input('Entre com um número inteiro: '))
for i in range (1,n+1):
  s = s+i
print(f'soma = {s}')

s = 0
n = int(input('Entre com um número inteiro: '))
for i in range (1,n+1):
  s = s+i
  print(i,end='')
  if i < n:
    print(' + ',end='')
  else:
    print(' = ',end='')
print(s)

"""QUESTÃO 3"""

s = 1
n = int(input('Entre com um número inteiro: '))
for i in range (1,n+1):
  s = s*i
print(f'soma = {s}')

"""QUESTÃO 4"""

qtd = 20
print(f'Digite {qtd} números inteiros')
n = int(input())
maior = n
for i in range (qtd-1):
   n= int(input())
   if n >maior:
     maior = n
print('Maior =',maior)

maior = int(input())
for i in range (4):
   n= int(input())
   if n >maior:
     maior = n
print('Maior =',maior)

n = int(input())
maior = n
for i in range (3):
   n= int(input())
   if n >maior:
     maior = n
print('Maior =',maior)

qtd = 3
print(f'Digite {qtd} números inteiros')
n = int(input())
maior = n
for i in range (qtd-1):
   n= int(input())
   if n >maior:
     maior = n
print('Maior =',maior)

qtd = 3
maior = 0
menor = 1000
print(f'Digite a idade de {qtd} pessoas')
for i in range (qtd):
   nome = input('Digite um nome: ')
   idade= int(input())
   if idade >maior:
     maior = idade
     nomemaior = nome
   if idade < menor:
     menor = idade
     nomemenor = nome
print('Maior: ',nomemaior, maior)
print('Menor: ',nomemenor, menor)

"""QUESTÃO 5"""

qtdm = 0
qtdf = 0
qtd = int(input('Digite a quantidade de pessoas:'))

for i in range (qtd):
 sexo = input('Digite o sexo (F/M):') .upper
 if sexo == 'M':
  qtdm = qtdm + 1
 else:
   qtdf = qtdf + 1

percentm = qtdm/qtd *100
percentf = qtdf/qtd *100

print(f'A porcentagem de homens é {percentm}% e de mulheres é {percentf}%.')

contM = 0
contF = 0
n = int(input('Informe a quantidade de pessoas:'))

for i in range(n):
  sexo = input('Sexo(M/F)') .upper
  if sexo == 'M':
    contM = contM + 1
  else:
    contF = contF + 1
percM = contM/n *100
percF = contF/n *100
print(f'A porcentagem de homens é {percM}% e de mulheres é {percF}%.')

"""QUESTÃO 6"""

n = int(input('Digite um número inteiro n: '))
x = int(input('Digite um número inteiro x: '))
y = int(input('Digite um número inteiro y: '))
print('Os múltiplos de',n,'entre',x,'e',y,'são:')
for i in range (x,y+1):
  if i % n == 0:
      print(i,end=' ')

n = int(input('Digite um número inteiro n: '))
x = int(input('Digite um número inteiro x: '))
y = int(input('Digite um número inteiro y: '))
print('Os múltiplos de',n,'entre',x,'e',y,'são:')

if x > y:
 for i in range (y,x+1):
  if i % n == 0:
    print(i,end=' ')
else:
 for i in range (x,y+1):
  if i % n == 0:
      print(i,end=' ')

n = int(input('Digite um número inteiro n: '))
x = int(input('Digite um número inteiro x: '))
y = int(input('Digite um número inteiro y: '))
print('Os múltiplos de',n,'entre',x,'e',y,'são:')


if x > y:
  aux = x
  x = y
  y = aux

  for i in range (y,x+1):
   if i % n == 0:
    print(i,end=' ')

"""QUESTÃO 7"""

n = int(input('Digite um número inteiro: '))
cont = 0
for i in range(2,n):
  if n % i == 0:
    cont = cont + 1
if cont == 0 and n != 1:
  print('primo')
else:
  print('não é primo')

n = int(input('Digite um número inteiro: '))

if n == 1:
  primo = False
else:
  primo = True
  for i in range(2,n):
    if n % i == 0:
      primo = False

if primo:
    print(n,'é primo')
else:
    print(n,'não é primo')

"""QUESTÃO 8"""

import math
a = 0
n = int(input('Digite um número inteiro: '))
for i in range(1,n+1):
  raiz = math.sqrt(i)
  if raiz == int(raiz) and i > a:
    result = i
print(f'O maior quadrado perfeito é {result}')