# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njZpSdZbu2z81q5vmlraO57-dwk2exGq

Questão 1
"""

n = int(input('Digite um número inteiro: '))
if n % 2 == 0:
    result = 'Par'
else:
     result = 'Ímpar'
print(f'O número {n} é {result}')

n = int(input("Digite um número inteiro: "))
if n % 2 == 0:
  print('par')
else:
  print('ímpar')

"""Questão 2"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
if n2 > n1:
  print(f'{n1}, {n2}')
else:
  print(f'{n2}, {n1}')

n1 = int(input("Digite o 1° número: "))
n2 = int(input("Digite o 2° número: "))
if n1 > n2:
  print(n2,n1)
else:
  print(n1,n2)

"""Questão 3"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
n3 = int(input('Digite o terceiro número: '))
if n1 >= n2 and n3:
 result = n1
if n2 >= n1 and n3:
  result = n2
if n3 >= n1 and n3:
  result = n3
print(f'O maior é {result}')

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
n3 = int(input('Digite o terceiro número: '))
if n1 > n2 and n3:
 result = n1
elif n2 > n3:
  result = n2
else:
  result = n3
print(f'O maior é {result}')

"""Questão 4"""

nome = input('Nome: ')
sexo = input('Sexo(M/F):').upper()
if sexo == 'M':
  trat = 'Sr.'
else:
  trat = 'Sra.'
print(f'Olá, {trat} {nome}!')

sex1 = 'F'
sex2 = 'M'
nome = input('Digite o nome: ')
sexo = input('Digite o sexo: ')
if sexo == sex1:
 print(f'Olá, Sra.{nome}')
else:
  print(f'Olá, Sr.{nome}')

nome = input("Digite o nome: ")
sexo = input("Digite o sexo(F/M): ").upper()
if sexo == "F":
  print(f"Olá, Sra. {nome}!")
else:
  print(f"Olá, Sr. {nome}!")

"""Questão 5"""

nome = input('Digite aqui o nome do vendedor: ')
totalven = float(input('Digite aqui o total de vendas do vendedor: '))
salariomin = float(input('Digite o valor do salário mínimo atual: '))
salariofim = totalven * 0.05
if salariofim > salariomin:
 print(f'O salário do funcionário {nome}, é: {salariofim}')
else:
   print(f'O salário do funcionário {nome}, é {salariomin}')

nome = input('Digite aqui o nome do vendedor: ')
totalven = int(input('Digite aqui o total de vendas do vendedor: '))
salariomin = 1320
salariofim = (totalven*5)//100
if salariofim >  salariomin:
 print(f'O salário do funcionário {nome}, é: {salariofim}')
else:
   print(f'O salário do funcionário {nome}, é {salariomin}')

vendas = float(input('Total de vendas: R$'))
comissão = vendas * 5/100
if comissão <= 1320.00:
  salario = 1320.00
else:
  salario = comissão
print(f'Salário = R$ {salario:.2f}')

"""Questão 6"""

conceito_a = 'fortemente recomendado/a'
conceito_b_c = 'recomendado/a'
conceito_d = 'não recomendado/a'
nome = input('Digite o nome do estudante: ')
conceito = input('Digite o conceito do estudante: ')
if conceito == 'A' or conceito == 'a':
 result = conceito_a
elif conceito == 'B' or 'b' or 'C' or 'c':
  result = conceito_b_c
else:
  result = conceito_d
print(f'A recomendação do estudante {nome} é {result}.')

nome = input('Digite o nome do estudante: ')
conceito = input('Digite o conceito do estudante: ')
if conceito == 'A' or conceito == 'a':
 result = 'fortemente recomendado/a'
elif conceito == 'B' or conceito == 'b' or conceito == 'C' or conceito == 'c':
  result = 'recomendado/a'
else:
  result = 'não recomendado/a'
print(f'A recomendação do estudante {nome} é {result}.')

nome = input('Digite o nome do estudante: ')
conceito = input('Digite o conceito do estudante: ').upper()
if conceito == 'A':
 result = 'fortemente recomendado/a'
elif conceito == 'B' or conceito == 'C':
  result = 'recomendado/a'
else:
  result = 'não recomendado/a'
print(f'A recomendação do estudante {nome} é {result}.')

"""Questão 7"""

peso = float(input('Digite aqui o peso (kg): '))
altura = float(input('Digite sua altura (m): '))
imc = peso/(altura ** 2)
if imc < 18.5:
 result = 'baixo peso'
elif imc < 25:
 result = 'normal'
elif imc < 30:
  result = 'sobrepeso'
else:
  result = 'obesidade'
print(f'O grau de obesidade é: {result}')

peso = float(input('Digite aqui o peso (kg): '))
altura = float(input('Digite sua altura (m): '))
imc = peso/(altura*altura)
if imc < 18.5:
 result = 'baixo peso'
elif imc >= 18.5 and imc < 25:
 result = 'normal'
elif imc >= 25 and imc < 30:
  result = 'sobrepeso'
else:
  result = 'obesidade'
print(f'O grau de obesidade é: {result}')

"""Questão 8"""

num1 = int(input('1° operando: '))
num2 = int(input('2° operando: '))
op = input('operador: ').lower()
if op == '+' or op == 'soma':
  print(num1 + num2)
elif op == '-' or op == 'subtração':
  print(num1 - num2)
elif op == 'x' or op == 'multiplicação':
  print(num1 * num2)
elif op == '/' or op == 'divisão':
  print(num1 / num2)
elif op == '%':
  print(num1 % num2)
else:
  print('Operador desconhecido')

num1 = int(input('1° operando: '))
num2 = int(input('2° operando: '))
op = input('operador: ').lower()
if op == '+':
  print(num1 + num2)
elif op == '-':
  print(num1 - num2)
elif op == 'x':
  print(num1 * num2)
elif op == '/':
  print(num1 / num2)
elif op == '%':
  print(num1 % num2)
else:
  print('Operador desconhecido')