# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jrQIUwhdVNP-ZBudbAoKpfb8jbzBm42

**QUESTÃO 1**
"""

#professor
#1. Escreva um programa que leia um vetor A de N números inteiros (N será lido) e um outro inteiro K, construa e exiba um outro vetor B cujos elementos são os respectivos elementos de a multiplicados por K.
#Ex: A = [1,2,3], K = 5, B = [5,10,15].

n = int(input('Digite o número de elementos: '))
a = [None]*n
b = [None]*n

#leitura do vetor a
print('Informe os valores dos elementos do vetor a: ')
for i in range(n):
  a[i] = int(input(f'A[{i}]: '))

#leitura do valor k
k = int(input('Informe o valor de K: '))

#cálculo de b
for i in range(n):
  b[i] = a[i]*k

#exibição dos resultados
print(f'A = {a}')
print(f'K = {k}')
print(f'B = {b}')

"""**QUESTÃO 2**"""

#sem novas "tags"
#Escreva um programa que leia um vetor V (contendo 30 inteiros) e um valor inteiro K, calcule e exiba a quantidade de ocorrências de K dentro de V.
n = 5  #por praticidade coloquei 5
v = [None]*n

print('Informe os elementos do vetor: ')
for i in range(n):
 v[i] = int(input())

k = int(input('Informe o valor a ser contado: '))

cont = 0
for e in v:
  if e == k:
    cont += 1
print(f'{k} ocorre {cont} vezes dentro do vetor.')

#com novas "tags"
import random
n = 30
v = [None]*n

print('Informe os elementos do vetor: ')
for i in range(n):
 v[i] = random.randint(1,10) #para pegar números no aleatório, o computador escolhe
print(v)

k = int(input('Informe o valor a ser contado: '))
print(v.count(k))

#professor
#Escreva um programa que leia um vetor V (contendo 30 inteiros) e um valor inteiro K, calcule e exiba a quantidade de ocorrências de K dentro de V.
import random
n = 30
v = [None]*n

print('Informe os elementos do vetor: ')
for i in range(n):
 v[i] = random.randint(1,10) #para pegar números no aleatório, o computador escolhe
print(v)

k = int(input('Informe o valor a ser contado: '))

cont = 0
for e in v:
  if e == k:
    cont += 1
print(f'{k} ocorre {cont} vezes dentro do vetor.')

"""**QUESTÃO 3**"""

#sem novas "tags"
#Escreva um programa que leia um vetor V contendo N elementos inteiros (N será lido) e um valor inteiro K, verifique e exiba se o K está ou não no vetor. Se estiver, informe em que posição (índice).
#Obs: K pode se repetir no vetor, nesse caso, mostre todas as posições onde o K aparece.

n = int(input('Digite a quantidade de vetores: '))
v = [None]*n #para poder pegar a quantidade que coloquei

print('Informe os elementos do vetor: ')
for i in range(n):
  v[i] = int(input()) #ele botou aleatório, mas tá certo

k = int(input('Informe o valor a ser contado: '))

for i in range(n):
  if v[i] == k:
   print(f'{k} está contido no vetor.')
   print(f'Suas posições são: {i}')
if v[i] != k:
  print(f'{k} não está contido no vetor.') #errei pq botei essa decisão dentro, ela tinha que ser antes/fora



#professor
import random
n = int(input('Digite a quantidade de vetores: '))
v = [None]*n

print('Informe os elementos do vetor: ')
for i in range(n):
 v[i] = random.randint(1,10)
print(v)

k = int(input('Informe o valor a ser contado: '))

if v.count(k) > 0:
 print(f'{k} está contido no vetor. ')
 for i in range(n):
  if v[i] == k:
   print(f'Suas posições são: {i}')
else:
 print(f'{k} não está contido no vetor.')

"""**QUESTÃO 4**"""

#Escreva um programa que leia 10 números e armazene-os em um vetor. Exiba:
# Os números que estão nos índices pares;
# Os números que estão nos índices ímpares.

n = 3
v = [None]*n

print('Digite os elementos do vetor:')
for i in range(n):
  v[i] = int(input())
for i in range(n):
  if i % 2 == 0:
   print([i])
for i in range (n):
   if i % 2 != 0:
    print([i])

#professor
n = 5
v = [None]*n

print('Digite os elementos do vetor:')
for i in range(n):
  v[i] = int(input())
for i in range(0,n,2):
 print(v[i])
for i in range (1,n,2):
 print(v[i])

"""**QUESTÃO 5**"""

#sem usar as novas "tags"

#com novas"tags"
#Escreva um programa que receba um vetor V de N números inteiros (N será lido), determine e exiba o maior e o menor elemento deste vetor e seus respectivos índices.
#Obs: suponha a inexistência de valores repetidos.

n = int(input('Digite os elementos do vetor: '))
v = [None]*n
print('Digite os elementos do vetor: ')
for i in range(n):
  v[i] = int(input())
print(f'O maior é: ', max(v))
print(f'O menor é: ', min(v))

#professor
n = int(input('Digite a quantidade de8 elementos do vetor: '))
v = [None]*n
print('Digite os elementos do vetor: ')
for i in range(n):
  v[i] = int(input())
maior = max(v)
menor = min(v)
indmaior = v.index(maior)
indmenor = v.index(menor)
print(f'O maior é: {maior}, e seu índice é: {indmaior}')
print(f'O menor é: {menor}, e seu índice é: {indmenor}')

"""**QUESTÃO 6**"""

#sem usar as novas "tags"

#com novas "tags"
#Escreva um programa que leia um vetor de N números inteiros (N será lido), inverta a ordem dos elementos do vetor e exiba o vetor invertido. Ex: V = [1, 3, 5, 7], após a inversão: V = [7, 5, 3, 1].
#Obs: É necessário inverter os elementos do vetor, não basta imprimi-los em ordem inversa!
n = int(input('Digite a quantidade de vetores: '))
v = [None]*n
print('Digite os elementos do vetor: ')
for i in range(n):
  v[i] = int(input())
print(v)
v.reverse()
print(v)

#professor