# -*- coding: utf-8 -*-
"""APE - EXERCÍCIOS 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HirtY6sy3qIKcwGskB6ta81QvJ3ydGMe
"""

t=input('Bem-vindo ao mundo da programação!')

x = int(input(‘Digite um número: ‘))
d = x * 2
print(‘O dobro de {} vale {}.’. format(x, d))

numero1=input("Digite um número: ")
numero2=input("Digite um número: ")
soma=int(numero1)+int(numero2)
print(soma)

base = int(input("Digite um número para base: "))
altura = int(input("Digite um número para altura: "))
area = (base*altura)/2
print("A área do triângulo é:",area)

nome = input('Digite um nome: ')
sobrenome = input('Digite um sobrenome: ')
print(sobrenome, ',', nome)

dolar = float(input('Digite o valor em dólares: '))
cot = float(input('Digite a cotação do dólar: '))
convers = (dolar*cot*real)
print(f'O valor total corresponde a: {convers}')

kg = float(input('Digite o Kg: '))
preco = float(input('Digite o valor por Kg: '))
res = (kg*preco)
print(f' O valor a pagar é: {res}')

nome = input ('Digite um nome: ')
semestre1 = input ('Digite o semestre: ')
n1 = float(input('Primeira nota do aluno: '))
n2 = float(input('Segunda nota do aluno: '))
n3 = float(input('Terceira nota do aluno: '))
média = (n1 + n2 + n3) / 3
print(f'A média de {nome} entre {n1}, {n2} e {n3} é igual a {média}')