from ArvoreBinaria import ArvoreBinaria, ArvoreException

arv = ArvoreBinaria(70)
print('Onde estou?',arv.getCursor())
arv.addFilhoEsquerdo(2)
arv.addFilhoDireito(15)
arv.descer_para_direita()
arv.addFilhoDireito(777)
arv.addFilhoEsquerdo(10)
arv.descer_para_esquerda()
print('Onde estou?',arv.getCursor())
arv.addFilhoEsquerdo(13)
arv.addFilhoDireito(22)
arv.descer_para_direita()
arv.addFilhoDireito(0)
arv.preordem()
print()
arv.emordem()
print()
arv.posordem()
print('Busca: ', arv.busca(778))
arv.esvazia()
print()
arv.preordem()
print(arv.estaVazia())
input('...')


print('Onde estou?',arv.getCursor())
print(arv)
#print(arv.__dict__)
print(arv.getRaiz())
print(arv.getCursor())
arv.descer_para_direita()
print(arv.getCursor())
